template = ""
rev_id = 331
template_sha = "8cacf2c4546a4e46881bd306e8c347aa8b1ae938"

[replacements]
__GLOTTOLOG_ID__ = "umes1235"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-sju"
__UND2C__ = "sju"
__UNDEFINED__ = "Ume Sami"
__UND__ = "sju"
