template = ""
rev_id = 336
template_sha = "389e4bc166fb75b7405a9d137e775aeee3aae1fb"

[replacements]
__GLOTTOLOG_ID__ = "umes1235"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-sju"
__UND2C__ = "sju"
__UNDEFINED__ = "Ume Sami"
__UND__ = "sju"
