template = ""
rev_id = 343
template_sha = "6a87b02e69420951013c6496773f7a9880f0f5f2"

[replacements]
__GLOTTOLOG_ID__ = "umes1235"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-sju"
__UND2C__ = "sju"
__UNDEFINED__ = "Ume Sami"
__UND__ = "sju"
